token: 1234:wxyz
adm_chat: -1001120079552
chats:
  ts: -1001120079552
  tv: 123
captcha:
  timeout: 60 # seconds
  msg_limit: 5
graphs:
  orca:
    remote: true
    url: http://localhost:9091
  period: 1 # hours
db:
  users: 'users.json'
  messages: 'messages.db'
